const wallpapers = {
  'bestWallpapers': [
    'assets/images/best/minimal 1.png',
    'assets/images/best/minimal_moon 1.png',
    'assets/images/best/minimal_wallpaper (1) 1.png',
    'assets/images/best/minimal_wallpaper 1.png',
  ],
  'abstractImages': [
    'assets/images/abstract/abstract (1).jpg',
    'assets/images/abstract/abstract (2).jpg',
    'assets/images/abstract/abstract (3).jpg',
    'assets/images/abstract/abstract (4).jpg',
    'assets/images/abstract/abstract_cubes.jpg',
    'assets/images/abstract/abstract_design.jpg',
    'assets/images/abstract/abstract.jpg',
  ],
  'natureImages': [
    'assets/images/nature/beach 1.png',
    'assets/images/nature/hills 1.png',
    'assets/images/nature/nature_hd 1.png',
    'assets/images/nature/nature_landscape (1) 1.png',
    'assets/images/nature/nature_landscape 1.png',
    'assets/images/nature/nature_wallpaper (1) 1.png',
    'assets/images/nature/nature_wallpaper 1.png',
    'assets/images/nature/river 1.png',
  ],
  'carsImage': [
    'assets/images/cars/car (1) 1.png',
    'assets/images/cars/car (2) 1.png',
    'assets/images/cars/car (3) 1.png',
    'assets/images/cars/car (4) 1.png',
    'assets/images/cars/car 1.png',
    'assets/images/cars/car-bmw 1.png',
    'assets/images/cars/cars 1.png',
  ],
  'animeImages': [
    'assets/images/anime/anime_girl 1.png',
    'assets/images/anime/anime_wallpaper (1) 1.png',
    'assets/images/anime/anime_wallpaper 1.png',
    'assets/images/anime/anime_wallpaper_ (1) 1.png',
    'assets/images/anime/anime_wallpaper_ 1.png',
    'assets/images/anime/anime_wallpaper_levi 1.png',
    'assets/images/anime/wallpaper_anime_ 1.png',
    'assets/images/anime/wallpapers_anime_ 1.png',
  ],
};
